USE EnterpriseDB_Helper

/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 743,'Ackworth',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 744,'Adair',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 745,'Adel',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 746,'Afton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 747,'Agency',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 748,'Ainsworth',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 749,'Akron',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 750,'Albert City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 751,'Albia',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 752,'Albion',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 753,'Alburnett',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 754,'Alden',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 755,'Alexander',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 756,'Algona',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 757,'Alleman',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 758,'Allerton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 759,'Allison',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 760,'Alta',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 761,'Alta Vista',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 762,'Alton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 763,'Altoona',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 764,'Alvord',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 765,'Amana',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 766,'Ames',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 767,'Anamosa',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 768,'Anderson',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 769,'Andover',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 770,'Andrew',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 771,'Anita',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 772,'Ankeny',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 773,'Anthon',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 774,'Aplington',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 775,'Arcadia',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 776,'Archer',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 777,'Aredale',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 778,'Arion',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 779,'Arispe',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 780,'Arlington',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 781,'Armstrong',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 782,'Arnolds Park',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 783,'Arthur',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 784,'Asbury',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 785,'Ashton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 786,'Aspinwall',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 787,'Atalissa',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 788,'Athelstan',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 789,'Atkins',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 790,'Atlantic',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 791,'Auburn',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 792,'Audubon',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 793,'Aurelia',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 794,'Aurora',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 795,'Avoca',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 796,'Ayrshire',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 797,'Badger',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 798,'Bagley',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 799,'Baldwin',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 800,'Balltown',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 801,'Bancroft',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 802,'Bankston',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 803,'Barnes City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 804,'Barnum',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 805,'Bartlett',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 806,'Bassett',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 807,'Batavia',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 808,'Battle Creek',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 809,'Baxter',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 810,'Bayard',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 811,'Beacon',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 812,'Beaconsfield',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 813,'Beaman',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 814,'Beaver',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 815,'Beaverdale',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 816,'Bedford',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 817,'Belle Plaine',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 818,'Bellevue',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 819,'Belmond',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 820,'Bennett',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 821,'Bentley',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 822,'Benton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 823,'Berkley',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 824,'Bernard',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 825,'Bertram',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 826,'Bettendorf',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 827,'Bevington',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 828,'Birmingham',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 829,'Blairsburg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 830,'Blairstown',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 831,'Blakesburg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 832,'Blanchard',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 833,'Blencoe',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 834,'Blockton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 835,'Bloomfield',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 836,'Blue Grass',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 837,'Bode',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 838,'Bolan',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 839,'Bonaparte',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 840,'Bondurant',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 841,'Boone',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 842,'Bouton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 843,'Boxholm',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 844,'Boyden',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 845,'Braddyville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 846,'Bradford',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 847,'Bradgate',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 848,'Brandon',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 849,'Brayton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 850,'Breda',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 851,'Bridgewater',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 852,'Brighton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 853,'Bristow',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 854,'Britt',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 855,'Bronson',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 856,'Brooklyn',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 857,'Brunsville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 858,'Buckeye',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 859,'Buck Grove',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 860,'Buffalo',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 861,'Buffalo Center',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 862,'Burchinal',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 863,'Burlington',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 864,'Burr Oak',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 865,'Burt',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 866,'Bussey',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 867,'Calamus',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 868,'California Junction',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 869,'Callender',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 870,'Calmar',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 871,'Calumet',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 872,'Camanche',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 873,'Cambridge',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 874,'Cantril',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 875,'Carbon',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 876,'Carlisle',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 877,'Carpenter',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 878,'Carroll',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 879,'Carson',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 880,'Carter Lake',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 881,'Cascade',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 882,'Casey',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 883,'Castalia',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 884,'Castana',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 885,'Cedar Falls',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 886,'Cedar Rapids',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 887,'Center Junction',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 888,'Center Point',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 889,'Centerville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 890,'Central City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 891,'Centralia',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 892,'Chapin',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 893,'Chariton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 894,'Charles City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 895,'Charlotte',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 896,'Charter Oak',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 897,'Chatsworth',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 898,'Chelsea',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 899,'Cherokee',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 900,'Chester',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 901,'Chillicothe',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 902,'Churdan',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 903,'Cincinnati',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 904,'Clare',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 905,'Clarence',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 906,'Clarinda',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 907,'Clarion',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 908,'Clarksville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 909,'Clayton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 910,'Clearfield',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 911,'Clear Lake',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 912,'Cleghorn',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 913,'Clemons',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 914,'Clermont',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 915,'Climbing Hill',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 916,'Clinton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 917,'Clio',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 918,'Clive',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 919,'Clutier',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 920,'Coalville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 921,'Coburg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 922,'Coggon',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 923,'Coin',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 924,'Colesburg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 925,'Colfax',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 926,'College Springs',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 927,'Collins',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 928,'Colo',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 929,'Columbus City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 930,'Columbus Junction',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 931,'Colwell',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 932,'Conesville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 933,'Conrad',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 934,'Conroy',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 935,'Conway',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 936,'Coon Rapids',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 937,'Coppock',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 938,'Coralville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 939,'Corley',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 940,'Corning',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 941,'Correctionville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 942,'Corwith',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 943,'Corydon',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 944,'Cotter',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 945,'Coulter',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 946,'Council Bluffs',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 947,'Craig',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 948,'Crawfordsville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 949,'Crescent',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 950,'Cresco',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 951,'Creston',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 952,'Cromwell',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 953,'Crystal Lake',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 954,'Cumberland',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 955,'Cumming',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 956,'Curlew',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 957,'Cushing',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 958,'Cylinder',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 959,'Dakota City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 960,'Dallas Center',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 961,'Dana',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 962,'Danbury',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 963,'Danville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 964,'Davenport',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 965,'Davis City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 966,'Dawson',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 967,'Dayton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 968,'Decatur City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 969,'Decorah',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 970,'Dedham',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 971,'Deep River',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 972,'Defiance',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 973,'Delaware',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 974,'Delhi',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 975,'Delmar',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 976,'Deloit',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 977,'Delphos',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 978,'Delta',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 979,'Denison',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 980,'Denmark',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 981,'Denver',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 982,'Derby',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 983,'Des Moines',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 984,'De Soto',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 985,'DeWitt',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 986,'De Witt',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 987,'Dexter',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 988,'Diagonal',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 989,'Diamondhead Lake',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 990,'Dickens',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 991,'Dike',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 992,'Dixon',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 993,'Dolliver',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 994,'Donahue',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 995,'Donnellson',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 996,'Doon',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 997,'Douds',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 998,'Dougherty',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 999,'Dow City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1000,'Dows',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1001,'Drakesville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1002,'Dubuque',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1003,'Dumont',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1004,'Duncan',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1005,'Duncombe',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1006,'Dundee',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1007,'Dunkerton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1008,'Dunlap',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1009,'Durango',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1010,'Durant',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1011,'Dyersville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1012,'Dysart',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1013,'Eagle Grove',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1014,'Earlham',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1015,'Earling',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1016,'Earlville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1017,'Early',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1018,'East Amana',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1019,'East Peru',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1020,'Eddyville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1021,'Edgewood',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1022,'Elberon',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1023,'Eldon',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1024,'Eldora',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1025,'Eldridge',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1026,'Elgin',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1027,'Elkader',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1028,'Elkhart',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1029,'Elk Horn',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1030,'Elkport',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1031,'Elk Run Heights',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1032,'Elliott',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1033,'Ellston',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1034,'Ellsworth',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1035,'Elma',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1036,'Ely',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1037,'Emerson',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1038,'Emmetsburg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1039,'Epworth',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1040,'Essex',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1041,'Estherville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1042,'Evansdale',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1043,'Everly',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1044,'Exira',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1045,'Exline',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1046,'Fairbank',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1047,'Fairfax',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1048,'Fairfield',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1049,'Farley',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1050,'Farmersburg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1051,'Farmington',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1052,'Farnhamville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1053,'Farragut',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1054,'Fayette',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1055,'Fenton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1056,'Ferguson',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1057,'Fertile',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1058,'Floris',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1059,'Floyd',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1060,'Fonda',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1061,'Fontanelle',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1062,'Forest City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1063,'Fort Atkinson',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1064,'Fort Dodge',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1065,'Fort Madison',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1066,'Fostoria',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1067,'Franklin',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1068,'Fraser',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1069,'Fredericksburg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1070,'Frederika',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1071,'Fredonia',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1072,'Fremont',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1073,'Fruitland',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1074,'Frytown',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1075,'Galt',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1076,'Galva',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1077,'Garber',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1078,'Garden City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1079,'Garden Grove',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1080,'Garnavillo',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1081,'Garner',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1082,'Garrison',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1083,'Garwin',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1084,'Geneva',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1085,'George',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1086,'Gibson',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1087,'Gilbert',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1088,'Gilbertville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1089,'Gillett Grove',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1090,'Gilman',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1091,'Gilmore City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1092,'Gladbrook',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1093,'Glenwood',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1094,'Glidden',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1095,'Goldfield',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1096,'Goodell',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1097,'Goose Lake',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1098,'Gowrie',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1099,'Graettinger',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1100,'Graf',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1101,'Grafton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1102,'Grand Junction',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1103,'Grand Mound',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1104,'Grand River',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1105,'Grandview',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1106,'Granger',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1107,'Grant',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1108,'Granville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1109,'Gravity',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1110,'Gray',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1111,'Greeley',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1112,'Greene',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1113,'Greenfield',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1114,'Green Mountain',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1115,'Greenville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1116,'Grimes',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1117,'Grinnell',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1118,'Griswold',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1119,'Grundy Center',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1120,'Gruver',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1121,'Guernsey',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1122,'Guthrie Center',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1123,'Guttenberg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1124,'Halbur',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1125,'Hamburg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1126,'Hamilton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1127,'Hampton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1128,'Hancock',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1129,'Hanlontown',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1130,'Hansell',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1131,'Harcourt',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1132,'Hardy',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1133,'Harlan',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1134,'Harper',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1135,'Harpers Ferry',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1136,'Harris',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1137,'Hartford',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1138,'Hartley',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1139,'Hartwick',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1140,'Harvey',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1141,'Hastings',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1142,'Havelock',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1143,'Haverhill',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1144,'Hawarden',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1145,'Hawkeye',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1146,'Hayesville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1147,'Hayfield',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1148,'Hazleton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1149,'Hedrick',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1150,'Henderson',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1151,'Hepburn',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1152,'Hiawatha',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1153,'High Amana',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1154,'Hills',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1155,'Hillsboro',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1156,'Hinton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1157,'Holiday Lake',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1158,'Holland',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1159,'Holstein',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1160,'Holy Cross',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1161,'Homestead',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1162,'Hopkinton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1163,'Hornick',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1164,'Hospers',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1165,'Houghton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1166,'Hubbard',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1167,'Hudson',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1168,'Hull',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1169,'Humboldt',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1170,'Humeston',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1171,'Hutchins',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1172,'Huxley',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1173,'Ida Grove',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1174,'Imogene',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1175,'Independence',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1176,'Indianola',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1177,'Inwood',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1178,'Ionia',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1179,'Iowa City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1180,'Iowa Falls',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1181,'Ireton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1182,'Irvington',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1183,'Irwin',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1184,'Jackson Junction',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1185,'Jacksonville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1186,'Jamaica',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1187,'Janesville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1188,'Jefferson',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1189,'Jesup',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1190,'Jewell Junction',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1191,'Johnston',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1192,'Joice',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1193,'Jolley',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1194,'Kalona',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1195,'Kamrar',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1196,'Kanawha',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1197,'Kellerton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1198,'Kelley',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1199,'Kellogg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1200,'Kensett',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1201,'Kent',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1202,'Keokuk',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1203,'Keomah Village',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1204,'Keosauqua',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1205,'Keota',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1206,'Keswick',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1207,'Keystone',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1208,'Kimballton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1209,'Kingsley',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1210,'Kinross',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1211,'Kirkman',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1212,'Kirkville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1213,'Kiron',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1214,'Klemme',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1215,'Knierim',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1216,'Knoxville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1217,'Lacona',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1218,'Ladora',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1219,'Lake City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1220,'Lake Mills',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1221,'Lake Panorama',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1222,'Lake Park',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1223,'Lakeside',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1224,'Lake View',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1225,'Lakota',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1226,'Lambs Grove',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1227,'Lamoni',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1228,'Lamont',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1229,'La Motte',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1230,'Lanesboro',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1231,'Lansing',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1232,'La Porte City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1233,'Larchwood',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1234,'Larrabee',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1235,'Latimer',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1236,'Laurel',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1237,'Laurens',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1238,'Lawler',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1239,'Lawton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1240,'Leando',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1241,'Le Claire',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1242,'Ledyard',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1243,'Le Grand',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1244,'Lehigh',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1245,'Leighton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1246,'Leland',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1247,'Le Mars',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1248,'Lenox',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1249,'Leon',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1250,'Le Roy',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1251,'Lester',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1252,'Letts',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1253,'Lewis',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1254,'Libertyville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1255,'Lidderdale',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1256,'Lime Springs',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1257,'Lincoln',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1258,'Linden',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1259,'Lineville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1260,'Linn Grove',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1261,'Lisbon',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1262,'Liscomb',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1263,'Little Cedar',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1264,'Little Rock',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1265,'Little Sioux',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1266,'Livermore',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1267,'Lockridge',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1268,'Logan',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1269,'Lohrville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1270,'Lone Rock',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1271,'Lone Tree',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1272,'Long Grove',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1273,'Lorimor',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1274,'Lost Nation',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1275,'Loveland',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1276,'Lovilia',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1277,'Lowden',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1278,'Low Moor',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1279,'Luana',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1280,'Lucas',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1281,'Luther',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1282,'Lu Verne',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1283,'Luxemburg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1284,'Luzerne',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1285,'Lynnville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1286,'Lytton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1287,'Macedonia',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1288,'Macksburg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1289,'Madrid',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1290,'Magnolia',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1291,'Maharishi Vedic City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1292,'Malcom',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1293,'Mallard',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1294,'Maloy',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1295,'Malvern',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1296,'Manchester',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1297,'Manilla',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1298,'Manly',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1299,'Manning',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1300,'Manson',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1301,'Mapleton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1302,'Maquoketa',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1303,'Marathon',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1304,'Marble Rock',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1305,'Marcus',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1306,'Marengo',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1307,'Marion',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1308,'Marne',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1309,'Marquette',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1310,'Marshalltown',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1311,'Martelle',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1312,'Martensdale',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1313,'Martinsburg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1314,'Marysville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1315,'Mason City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1316,'Masonville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1317,'Massena',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1318,'Matlock',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1319,'Maurice',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1320,'Maxwell',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1321,'Maynard',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1322,'Maysville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1323,'McCallsburg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1324,'McCausland',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1325,'McClelland',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1326,'McGregor',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1327,'McIntire',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1328,'Mechanicsville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1329,'Mediapolis',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1330,'Melbourne',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1331,'Melcher-Dallas',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1332,'Melrose',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1333,'Melvin',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1334,'Menlo',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1335,'Meriden',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1336,'Merrill',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1337,'Meservey',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1338,'Meyer',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1339,'Middle Amana',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1340,'Middletown',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1341,'Miles',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1342,'Milford',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1343,'Miller',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1344,'Millersburg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1345,'Millerton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1346,'Milo',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1347,'Milton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1348,'Minburn',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1349,'Minden',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1350,'Mineola',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1351,'Mingo',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1352,'Missouri Valley',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1353,'Mitchell',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1354,'Mitchellville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1355,'Modale',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1356,'Mona',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1357,'Mondamin',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1358,'Monmouth',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1359,'Monona',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1360,'Monroe',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1361,'Montezuma',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1362,'Monticello',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1363,'Montour',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1364,'Montrose',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1365,'Moorhead',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1366,'Moorland',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1367,'Moravia',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1368,'Morley',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1369,'Morning Sun',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1370,'Morrison',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1371,'Moulton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1372,'Mount Auburn',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1373,'Mount Ayr',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1374,'Mount Pleasant',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1375,'Mount Sterling',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1376,'Mount Union',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1377,'Mount Vernon',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1378,'Moville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1379,'Murray',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1380,'Muscatine',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1381,'Mystic',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1382,'Nashua',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1383,'Nemaha',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1384,'Neola',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1385,'Nevada',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1386,'New Albin',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1387,'Newell',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1388,'Newhall',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1389,'New Hampton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1390,'New Hartford',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1391,'New Haven',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1392,'New Liberty',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1393,'New London',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1394,'New Market',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1395,'New Providence',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1396,'New Sharon',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1397,'Newton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1398,'New Vienna',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1399,'New Virginia',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1400,'Nichols',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1401,'Nodaway',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1402,'Nora Springs',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1403,'Northboro',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1404,'North Buena Vista',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1405,'North English',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1406,'North Liberty',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1407,'North Washington',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1408,'Northwood',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1409,'Norwalk',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1410,'Norway',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1411,'Numa',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1412,'Oakland',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1413,'Oakland Acres',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1414,'Oakville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1415,'Ocheyedan',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1416,'Odebolt',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1417,'Oelwein',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1418,'Ogden',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1419,'Okoboji',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1420,'Olds',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1421,'Olin',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1422,'Ollie',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1423,'Onawa',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1424,'Onslow',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1425,'Orange City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1426,'Orchard',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1427,'Orient',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1428,'Orleans',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1429,'Osage',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1430,'Osceola',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1431,'Oskaloosa',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1432,'Ossian',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1433,'Osterdock',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1434,'Otho',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1435,'Oto',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1436,'Otranto',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1437,'Ottosen',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1438,'Ottumwa',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1439,'Owasa',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1440,'Oxford',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1441,'Oxford Junction',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1442,'Oyens',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1443,'Pacific Junction',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1444,'Packwood',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1445,'Palmer',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1446,'Palo',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1447,'Panama',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1448,'Panora',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1449,'Panorama Park',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1450,'Parkersburg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1451,'Park View',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1452,'Parnell',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1453,'Paton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1454,'Patterson',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1455,'Paullina',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1456,'Pella',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1457,'Peosta',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1458,'Percival',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1459,'Perry',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1460,'Persia',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1461,'Peterson',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1462,'Pierson',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1463,'Pilot Mound',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1464,'Pioneer',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1465,'Pisgah',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1466,'Plainfield',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1467,'Plano',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1468,'Pleasant Hill',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1469,'Pleasanton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1470,'Pleasant Plain',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1471,'Pleasantville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1472,'Plover',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1473,'Plymouth',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1474,'Pocahontas',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1475,'Polk City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1476,'Pomeroy',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1477,'Popejoy',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1478,'Portland',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1479,'Portsmouth',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1480,'Postville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1481,'Prairieburg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1482,'Prairie City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1483,'Prescott',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1484,'Preston',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1485,'Primghar',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1486,'Princeton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1487,'Promise City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1488,'Protivin',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1489,'Pulaski',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1490,'Quasqueton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1491,'Quimby',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1492,'Radcliffe',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1493,'Rake',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1494,'Ralston',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1495,'Randalia',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1496,'Randall',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1497,'Randolph',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1498,'Rathbun',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1499,'Raymond',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1500,'Readlyn',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1501,'Reasnor',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1502,'Redding',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1503,'Redfield',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1504,'Red Oak',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1505,'Reinbeck',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1506,'Rembrandt',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1507,'Remsen',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1508,'Renwick',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1509,'Rhodes',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1510,'Riceville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1511,'Richland',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1512,'Rickardsville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1513,'Ricketts',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1514,'Ridgeway',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1515,'Rinard',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1516,'Ringsted',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1517,'Rippey',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1518,'Riverdale',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1519,'Riverside',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1520,'River Sioux',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1521,'Riverton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1522,'Robins',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1523,'Rochester',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1524,'Rock Falls',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1525,'Rockford',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1526,'Rock Rapids',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1527,'Rock Valley',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1528,'Rockwell',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1529,'Rockwell City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1530,'Rodman',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1531,'Rodney',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1532,'Roland',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1533,'Rolfe',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1534,'Rome',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1535,'Rose Hill',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1536,'Roseville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1537,'Rossie',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1538,'Rowan',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1539,'Rowley',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1540,'Royal',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1541,'Rudd',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1542,'Runnells',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1543,'Russell',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1544,'Ruthven',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1545,'Rutland',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1546,'Ryan',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1547,'Sabula',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1548,'Sac City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1549,'Sageville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1550,'Salem',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1551,'Salix',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1552,'Sanborn',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1553,'Sandyville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1554,'Saylorville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1555,'Scarville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1556,'Schaller',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1557,'Schleswig',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1558,'Scranton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1559,'Searsboro',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1560,'Sergeant Bluff',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1561,'Sexton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1562,'Seymour',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1563,'Shambaugh',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1564,'Shannon City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1565,'Sharpsburg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1566,'Sheffield',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1567,'Shelby',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1568,'Sheldahl',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1569,'Sheldon',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1570,'Shell Rock',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1571,'Shellsburg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1572,'Shenandoah',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1573,'Sherrill',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1574,'Shueyville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1575,'Sibley',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1576,'Sidney',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1577,'Sigourney',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1578,'Silver City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1579,'Sioux Center',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1580,'Sioux City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1581,'Sioux Rapids',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1582,'Slater',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1583,'Sloan',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1584,'Smithland',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1585,'Soldier',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1586,'Solon',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1587,'Somers',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1588,'South Amana',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1589,'South English',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1590,'Spencer',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1591,'Spillville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1592,'Spirit Lake',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1593,'Spragueville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1594,'Springbrook',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1595,'Spring Hill',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1596,'Springville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1597,'Stacyville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1598,'Stanhope',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1599,'Stanley',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1600,'St. Ansgar',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1601,'St. Anthony',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1602,'Stanton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1603,'Stanwood',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1604,'State Center',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1605,'St. Benedict',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1606,'St. Charles',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1607,'St. Donatus',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1608,'Steamboat Rock',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1609,'St. Joseph',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1610,'St. Lucas',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1611,'St. Marys',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1612,'Stockport',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1613,'Stockton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1614,'St. Olaf',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1615,'Stone City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1616,'Storm Lake',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1617,'Story City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1618,'Stout',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1619,'St. Paul',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1620,'Stratford',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1621,'Strawberry Point',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1622,'Struble',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1623,'Stuart',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1624,'Sully',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1625,'Sumner',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1626,'Sun Valley Lake',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1627,'Superior',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1628,'Sutherland',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1629,'Swaledale',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1630,'Swan',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1631,'Swea City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1632,'Swisher',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1633,'Tabor',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1634,'Tama',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1635,'Templeton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1636,'Tennant',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1637,'Terril',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1638,'Thayer',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1639,'Thompson',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1640,'Thor',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1641,'Thornburg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1642,'Thornton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1643,'Thurman',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1644,'Tiffin',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1645,'Tingley',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1646,'Tipton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1647,'Titonka',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1648,'Toeterville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1649,'Toledo',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1650,'Toronto',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1651,'Traer',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1652,'Treynor',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1653,'Tripoli',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1654,'Truesdale',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1655,'Truro',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1656,'Turin',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1657,'Twin Lakes',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1658,'Udell',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1659,'Underwood',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1660,'Union',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1661,'Unionville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1662,'University Heights',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1663,'University Park',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1664,'Urbana',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1665,'Urbandale',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1666,'Ute',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1667,'Vail',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1668,'Valeria',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1669,'Van Horne',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1670,'Van Meter',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1671,'Van Wert',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1672,'Varina',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1673,'Ventura',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1674,'Victor',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1675,'Villisca',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1676,'Vincent',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1677,'Vining',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1678,'Vinton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1679,'Volga',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1680,'Wadena',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1681,'Wahpeton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1682,'Walcott',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1683,'Walford',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1684,'Walker',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1685,'Wallingford',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1686,'Wall Lake',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1687,'Walnut',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1688,'Wapello',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1689,'Washburn',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1690,'Washington',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1691,'Washta',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1692,'Waterloo',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1693,'Waterville',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1694,'Watkins',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1695,'Waucoma',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1696,'Waukee',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1697,'Waukon',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1698,'Waverly',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1699,'Wayland',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1700,'Webb',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1701,'Webster',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1702,'Webster City',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1703,'Weldon',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1704,'Wellman',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1705,'Wellsburg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1706,'Welton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1707,'Wesley',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1708,'West Amana',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1709,'West Bend',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1710,'West Branch',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1711,'West Burlington',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1712,'West Chester',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1713,'West Des Moines',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1714,'Westfield',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1715,'Westgate',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1716,'West Liberty',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1717,'West Okoboji',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1718,'Weston',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1719,'Westphalia',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1720,'West Point',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1721,'Westside',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1722,'West Union',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1723,'Westwood',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1724,'What Cheer',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1725,'Wheatland',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1726,'Whiting',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1727,'Whittemore',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1728,'Whitten',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1729,'Willey',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1730,'Williams',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1731,'Williamsburg',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1732,'Williamson',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1733,'Wilton',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1734,'Windsor Heights',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1735,'Winfield',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1736,'Winterset',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1737,'Winthrop',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1738,'Wiota',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1739,'Woden',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1740,'Woodbine',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1741,'Woodburn',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1742,'Woodward',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1743,'Woolstock',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1744,'Worthington',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1745,'Wyoming',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1746,'Yale',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1747,'Yetter',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1748,'Yorktown',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1749,'Zearing',1);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 1750,'Zwingle',1);
