//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Workflows.Invoker.UserRegistrationWorkflowService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserRegistrationWorkflowService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/StartRegistration", ReplyAction="http://tempuri.org/IService/StartRegistrationResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        Enterprise.Workflows.Invoker.UserRegistrationWorkflowService.StartRegistrationResponse StartRegistration(Enterprise.Workflows.Invoker.UserRegistrationWorkflowService.StartRegistrationRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/StartRegistration", ReplyAction="http://tempuri.org/IService/StartRegistrationResponse")]
        System.Threading.Tasks.Task<Enterprise.Workflows.Invoker.UserRegistrationWorkflowService.StartRegistrationResponse> StartRegistrationAsync(Enterprise.Workflows.Invoker.UserRegistrationWorkflowService.StartRegistrationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartRegistration", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StartRegistrationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public object userLoginObj;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public object userLoginRepository;
        
        public StartRegistrationRequest() {
        }
        
        public StartRegistrationRequest(object userLoginObj, object userLoginRepository) {
            this.userLoginObj = userLoginObj;
            this.userLoginRepository = userLoginRepository;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StartRegistrationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StartRegistrationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] lstSameRecord;
        
        public StartRegistrationResponse() {
        }
        
        public StartRegistrationResponse(bool result, string[] lstSameRecord) {
            this.result = result;
            this.lstSameRecord = lstSameRecord;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Enterprise.Workflows.Invoker.UserRegistrationWorkflowService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Enterprise.Workflows.Invoker.UserRegistrationWorkflowService.IService>, Enterprise.Workflows.Invoker.UserRegistrationWorkflowService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Enterprise.Workflows.Invoker.UserRegistrationWorkflowService.StartRegistrationResponse Enterprise.Workflows.Invoker.UserRegistrationWorkflowService.IService.StartRegistration(Enterprise.Workflows.Invoker.UserRegistrationWorkflowService.StartRegistrationRequest request) {
            return base.Channel.StartRegistration(request);
        }
        
        public bool StartRegistration(object userLoginObj, object userLoginRepository, out string[] lstSameRecord) {
            Enterprise.Workflows.Invoker.UserRegistrationWorkflowService.StartRegistrationRequest inValue = new Enterprise.Workflows.Invoker.UserRegistrationWorkflowService.StartRegistrationRequest();
            inValue.userLoginObj = userLoginObj;
            inValue.userLoginRepository = userLoginRepository;
            Enterprise.Workflows.Invoker.UserRegistrationWorkflowService.StartRegistrationResponse retVal = ((Enterprise.Workflows.Invoker.UserRegistrationWorkflowService.IService)(this)).StartRegistration(inValue);
            lstSameRecord = retVal.lstSameRecord;
            return retVal.result;
        }
        
        public System.Threading.Tasks.Task<Enterprise.Workflows.Invoker.UserRegistrationWorkflowService.StartRegistrationResponse> StartRegistrationAsync(Enterprise.Workflows.Invoker.UserRegistrationWorkflowService.StartRegistrationRequest request) {
            return base.Channel.StartRegistrationAsync(request);
        }
    }
}
