//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.WCF.Workflows.UserRegistrationServiceContract {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TblUserLogin", Namespace="http://schemas.datacontract.org/2004/07/Enterprise.DataLayers.EnterpriseDB_UserMo" +
        "del")]
    [System.SerializableAttribute()]
    public partial class TblUserLogin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserDetails UserDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserDetailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserLoginIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((this.PhoneNumberField.Equals(value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserDetails UserDetail {
            get {
                return this.UserDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDetailField, value) != true)) {
                    this.UserDetailField = value;
                    this.RaisePropertyChanged("UserDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserDetailId {
            get {
                return this.UserDetailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDetailIdField, value) != true)) {
                    this.UserDetailIdField = value;
                    this.RaisePropertyChanged("UserDetailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLogin {
            get {
                return this.UserLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLoginField, value) != true)) {
                    this.UserLoginField = value;
                    this.RaisePropertyChanged("UserLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLoginId {
            get {
                return this.UserLoginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLoginIdField, value) != true)) {
                    this.UserLoginIdField = value;
                    this.RaisePropertyChanged("UserLoginId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TblUserDetails", Namespace="http://schemas.datacontract.org/2004/07/Enterprise.DataLayers.EnterpriseDB_UserMo" +
        "del")]
    [System.SerializableAttribute()]
    public partial class TblUserDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressMainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressSecondaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressThirdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailMainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailSecondaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PhoneMainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PhoneSecondaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblPickUpLocation[] TblPickUpLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblProfileImage[] TblProfileImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserCard[] TblUserCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserLogin[] TblUserLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserDetailsIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressMain {
            get {
                return this.AddressMainField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressMainField, value) != true)) {
                    this.AddressMainField = value;
                    this.RaisePropertyChanged("AddressMain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressSecondary {
            get {
                return this.AddressSecondaryField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressSecondaryField, value) != true)) {
                    this.AddressSecondaryField = value;
                    this.RaisePropertyChanged("AddressSecondary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressThird {
            get {
                return this.AddressThirdField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressThirdField, value) != true)) {
                    this.AddressThirdField = value;
                    this.RaisePropertyChanged("AddressThird");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailMain {
            get {
                return this.EmailMainField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailMainField, value) != true)) {
                    this.EmailMainField = value;
                    this.RaisePropertyChanged("EmailMain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailSecondary {
            get {
                return this.EmailSecondaryField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailSecondaryField, value) != true)) {
                    this.EmailSecondaryField = value;
                    this.RaisePropertyChanged("EmailSecondary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PhoneMain {
            get {
                return this.PhoneMainField;
            }
            set {
                if ((this.PhoneMainField.Equals(value) != true)) {
                    this.PhoneMainField = value;
                    this.RaisePropertyChanged("PhoneMain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PhoneSecondary {
            get {
                return this.PhoneSecondaryField;
            }
            set {
                if ((this.PhoneSecondaryField.Equals(value) != true)) {
                    this.PhoneSecondaryField = value;
                    this.RaisePropertyChanged("PhoneSecondary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblPickUpLocation[] TblPickUpLocation {
            get {
                return this.TblPickUpLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.TblPickUpLocationField, value) != true)) {
                    this.TblPickUpLocationField = value;
                    this.RaisePropertyChanged("TblPickUpLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblProfileImage[] TblProfileImage {
            get {
                return this.TblProfileImageField;
            }
            set {
                if ((object.ReferenceEquals(this.TblProfileImageField, value) != true)) {
                    this.TblProfileImageField = value;
                    this.RaisePropertyChanged("TblProfileImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserCard[] TblUserCard {
            get {
                return this.TblUserCardField;
            }
            set {
                if ((object.ReferenceEquals(this.TblUserCardField, value) != true)) {
                    this.TblUserCardField = value;
                    this.RaisePropertyChanged("TblUserCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserLogin[] TblUserLogin {
            get {
                return this.TblUserLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.TblUserLoginField, value) != true)) {
                    this.TblUserLoginField = value;
                    this.RaisePropertyChanged("TblUserLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserDetailsId {
            get {
                return this.UserDetailsIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDetailsIdField, value) != true)) {
                    this.UserDetailsIdField = value;
                    this.RaisePropertyChanged("UserDetailsId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TblPickUpLocation", Namespace="http://schemas.datacontract.org/2004/07/Enterprise.DataLayers.EnterpriseDB_UserMo" +
        "del")]
    [System.SerializableAttribute()]
    public partial class TblPickUpLocation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PickUpLocation1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PickUpLocation2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PickUpLocation3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PickUpLocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserDetails UserDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserDetailIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickUpLocation1 {
            get {
                return this.PickUpLocation1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PickUpLocation1Field, value) != true)) {
                    this.PickUpLocation1Field = value;
                    this.RaisePropertyChanged("PickUpLocation1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickUpLocation2 {
            get {
                return this.PickUpLocation2Field;
            }
            set {
                if ((object.ReferenceEquals(this.PickUpLocation2Field, value) != true)) {
                    this.PickUpLocation2Field = value;
                    this.RaisePropertyChanged("PickUpLocation2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickUpLocation3 {
            get {
                return this.PickUpLocation3Field;
            }
            set {
                if ((object.ReferenceEquals(this.PickUpLocation3Field, value) != true)) {
                    this.PickUpLocation3Field = value;
                    this.RaisePropertyChanged("PickUpLocation3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickUpLocationId {
            get {
                return this.PickUpLocationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PickUpLocationIdField, value) != true)) {
                    this.PickUpLocationIdField = value;
                    this.RaisePropertyChanged("PickUpLocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserDetails UserDetail {
            get {
                return this.UserDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDetailField, value) != true)) {
                    this.UserDetailField = value;
                    this.RaisePropertyChanged("UserDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserDetailId {
            get {
                return this.UserDetailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDetailIdField, value) != true)) {
                    this.UserDetailIdField = value;
                    this.RaisePropertyChanged("UserDetailId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TblProfileImage", Namespace="http://schemas.datacontract.org/2004/07/Enterprise.DataLayers.EnterpriseDB_UserMo" +
        "del")]
    [System.SerializableAttribute()]
    public partial class TblProfileImage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileImageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileImageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProfileImageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserDetails UserDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserDetailIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileImageId {
            get {
                return this.ProfileImageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileImageIdField, value) != true)) {
                    this.ProfileImageIdField = value;
                    this.RaisePropertyChanged("ProfileImageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileImageName {
            get {
                return this.ProfileImageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileImageNameField, value) != true)) {
                    this.ProfileImageNameField = value;
                    this.RaisePropertyChanged("ProfileImageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProfileImageSize {
            get {
                return this.ProfileImageSizeField;
            }
            set {
                if ((this.ProfileImageSizeField.Equals(value) != true)) {
                    this.ProfileImageSizeField = value;
                    this.RaisePropertyChanged("ProfileImageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileImageUrl {
            get {
                return this.ProfileImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileImageUrlField, value) != true)) {
                    this.ProfileImageUrlField = value;
                    this.RaisePropertyChanged("ProfileImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserDetails UserDetail {
            get {
                return this.UserDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDetailField, value) != true)) {
                    this.UserDetailField = value;
                    this.RaisePropertyChanged("UserDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserDetailId {
            get {
                return this.UserDetailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDetailIdField, value) != true)) {
                    this.UserDetailIdField = value;
                    this.RaisePropertyChanged("UserDetailId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TblUserCard", Namespace="http://schemas.datacontract.org/2004/07/Enterprise.DataLayers.EnterpriseDB_UserMo" +
        "del")]
    [System.SerializableAttribute()]
    public partial class TblUserCard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardProviderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserCardIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserDetails UserDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserDetailsIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((this.CardNumberField.Equals(value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardOwner {
            get {
                return this.CardOwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.CardOwnerField, value) != true)) {
                    this.CardOwnerField = value;
                    this.RaisePropertyChanged("CardOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardProvider {
            get {
                return this.CardProviderField;
            }
            set {
                if ((object.ReferenceEquals(this.CardProviderField, value) != true)) {
                    this.CardProviderField = value;
                    this.RaisePropertyChanged("CardProvider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardType {
            get {
                return this.CardTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardTypeField, value) != true)) {
                    this.CardTypeField = value;
                    this.RaisePropertyChanged("CardType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserCardId {
            get {
                return this.UserCardIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserCardIdField, value) != true)) {
                    this.UserCardIdField = value;
                    this.RaisePropertyChanged("UserCardId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserDetails UserDetails {
            get {
                return this.UserDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDetailsField, value) != true)) {
                    this.UserDetailsField = value;
                    this.RaisePropertyChanged("UserDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserDetailsId {
            get {
                return this.UserDetailsIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDetailsIdField, value) != true)) {
                    this.UserDetailsIdField = value;
                    this.RaisePropertyChanged("UserDetailsId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserRegistrationServiceContract.IUserRegistrationService")]
    public interface IUserRegistrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRegistrationService/IsUserLoginExists", ReplyAction="http://tempuri.org/IUserRegistrationService/IsUserLoginExistsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserLogin))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblPickUpLocation[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblPickUpLocation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblProfileImage[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblProfileImage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserCard[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserCard))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserLogin[]))]
        Enterprise.WCF.Workflows.UserRegistrationServiceContract.IsUserLoginExistsResponse IsUserLoginExists(Enterprise.WCF.Workflows.UserRegistrationServiceContract.IsUserLoginExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRegistrationService/IsUserLoginExists", ReplyAction="http://tempuri.org/IUserRegistrationService/IsUserLoginExistsResponse")]
        System.Threading.Tasks.Task<Enterprise.WCF.Workflows.UserRegistrationServiceContract.IsUserLoginExistsResponse> IsUserLoginExistsAsync(Enterprise.WCF.Workflows.UserRegistrationServiceContract.IsUserLoginExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRegistrationService/GetSameRecord", ReplyAction="http://tempuri.org/IUserRegistrationService/GetSameRecordResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserLogin))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblPickUpLocation[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblPickUpLocation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblProfileImage[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblProfileImage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserCard[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserCard))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserLogin[]))]
        Enterprise.WCF.Workflows.UserRegistrationServiceContract.GetSameRecordResponse GetSameRecord(Enterprise.WCF.Workflows.UserRegistrationServiceContract.GetSameRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRegistrationService/GetSameRecord", ReplyAction="http://tempuri.org/IUserRegistrationService/GetSameRecordResponse")]
        System.Threading.Tasks.Task<Enterprise.WCF.Workflows.UserRegistrationServiceContract.GetSameRecordResponse> GetSameRecordAsync(Enterprise.WCF.Workflows.UserRegistrationServiceContract.GetSameRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRegistrationService/RegisterUser", ReplyAction="http://tempuri.org/IUserRegistrationService/RegisterUserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserLogin))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblPickUpLocation[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblPickUpLocation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblProfileImage[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblProfileImage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserCard[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserCard))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserLogin[]))]
        Enterprise.WCF.Workflows.UserRegistrationServiceContract.RegisterUserResponse RegisterUser(Enterprise.WCF.Workflows.UserRegistrationServiceContract.RegisterUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRegistrationService/RegisterUser", ReplyAction="http://tempuri.org/IUserRegistrationService/RegisterUserResponse")]
        System.Threading.Tasks.Task<Enterprise.WCF.Workflows.UserRegistrationServiceContract.RegisterUserResponse> RegisterUserAsync(Enterprise.WCF.Workflows.UserRegistrationServiceContract.RegisterUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRegistrationService/CreateUserLogin", ReplyAction="http://tempuri.org/IUserRegistrationService/CreateUserLoginResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserLogin))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblPickUpLocation[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblPickUpLocation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblProfileImage[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblProfileImage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserCard[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserCard))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserLogin[]))]
        Enterprise.WCF.Workflows.UserRegistrationServiceContract.CreateUserLoginResponse CreateUserLogin(Enterprise.WCF.Workflows.UserRegistrationServiceContract.CreateUserLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRegistrationService/CreateUserLogin", ReplyAction="http://tempuri.org/IUserRegistrationService/CreateUserLoginResponse")]
        System.Threading.Tasks.Task<Enterprise.WCF.Workflows.UserRegistrationServiceContract.CreateUserLoginResponse> CreateUserLoginAsync(Enterprise.WCF.Workflows.UserRegistrationServiceContract.CreateUserLoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUserLoginExists", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsUserLoginExistsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] sameRecord;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public object userLoginRepository;
        
        public IsUserLoginExistsRequest() {
        }
        
        public IsUserLoginExistsRequest(string[] sameRecord, object userLoginRepository) {
            this.sameRecord = sameRecord;
            this.userLoginRepository = userLoginRepository;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUserLoginExistsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsUserLoginExistsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool IsUserLoginExistsResult;
        
        public IsUserLoginExistsResponse() {
        }
        
        public IsUserLoginExistsResponse(bool IsUserLoginExistsResult) {
            this.IsUserLoginExistsResult = IsUserLoginExistsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSameRecord", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSameRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserLogin userLogin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public object userLoginRepository;
        
        public GetSameRecordRequest() {
        }
        
        public GetSameRecordRequest(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserLogin userLogin, object userLoginRepository) {
            this.userLogin = userLogin;
            this.userLoginRepository = userLoginRepository;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSameRecordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSameRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] GetSameRecordResult;
        
        public GetSameRecordResponse() {
        }
        
        public GetSameRecordResponse(string[] GetSameRecordResult) {
            this.GetSameRecordResult = GetSameRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegisterUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserLogin userLogin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public object userLoginRepository;
        
        public RegisterUserRequest() {
        }
        
        public RegisterUserRequest(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserLogin userLogin, object userLoginRepository) {
            this.userLogin = userLogin;
            this.userLoginRepository = userLoginRepository;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegisterUserResponse {
        
        public RegisterUserResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUserLogin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateUserLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public object value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public object userLoginRepository;
        
        public CreateUserLoginRequest() {
        }
        
        public CreateUserLoginRequest(object value, object userLoginRepository) {
            this.value = value;
            this.userLoginRepository = userLoginRepository;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUserLoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateUserLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserLogin CreateUserLoginResult;
        
        public CreateUserLoginResponse() {
        }
        
        public CreateUserLoginResponse(Enterprise.WCF.Workflows.UserRegistrationServiceContract.TblUserLogin CreateUserLoginResult) {
            this.CreateUserLoginResult = CreateUserLoginResult;
        }
    }
}
