CREATE TABLE [System.Activities.DurableInstancing].[InstancePromotedPropertiesTable] (
    [SurrogateInstanceId] BIGINT          NOT NULL,
    [PromotionName]       NVARCHAR (400)  NOT NULL,
    [Value1]              SQL_VARIANT     NULL,
    [Value2]              SQL_VARIANT     NULL,
    [Value3]              SQL_VARIANT     NULL,
    [Value4]              SQL_VARIANT     NULL,
    [Value5]              SQL_VARIANT     NULL,
    [Value6]              SQL_VARIANT     NULL,
    [Value7]              SQL_VARIANT     NULL,
    [Value8]              SQL_VARIANT     NULL,
    [Value9]              SQL_VARIANT     NULL,
    [Value10]             SQL_VARIANT     NULL,
    [Value11]             SQL_VARIANT     NULL,
    [Value12]             SQL_VARIANT     NULL,
    [Value13]             SQL_VARIANT     NULL,
    [Value14]             SQL_VARIANT     NULL,
    [Value15]             SQL_VARIANT     NULL,
    [Value16]             SQL_VARIANT     NULL,
    [Value17]             SQL_VARIANT     NULL,
    [Value18]             SQL_VARIANT     NULL,
    [Value19]             SQL_VARIANT     NULL,
    [Value20]             SQL_VARIANT     NULL,
    [Value21]             SQL_VARIANT     NULL,
    [Value22]             SQL_VARIANT     NULL,
    [Value23]             SQL_VARIANT     NULL,
    [Value24]             SQL_VARIANT     NULL,
    [Value25]             SQL_VARIANT     NULL,
    [Value26]             SQL_VARIANT     NULL,
    [Value27]             SQL_VARIANT     NULL,
    [Value28]             SQL_VARIANT     NULL,
    [Value29]             SQL_VARIANT     NULL,
    [Value30]             SQL_VARIANT     NULL,
    [Value31]             SQL_VARIANT     NULL,
    [Value32]             SQL_VARIANT     NULL,
    [Value33]             VARBINARY (MAX) NULL,
    [Value34]             VARBINARY (MAX) NULL,
    [Value35]             VARBINARY (MAX) NULL,
    [Value36]             VARBINARY (MAX) NULL,
    [Value37]             VARBINARY (MAX) NULL,
    [Value38]             VARBINARY (MAX) NULL,
    [Value39]             VARBINARY (MAX) NULL,
    [Value40]             VARBINARY (MAX) NULL,
    [Value41]             VARBINARY (MAX) NULL,
    [Value42]             VARBINARY (MAX) NULL,
    [Value43]             VARBINARY (MAX) NULL,
    [Value44]             VARBINARY (MAX) NULL,
    [Value45]             VARBINARY (MAX) NULL,
    [Value46]             VARBINARY (MAX) NULL,
    [Value47]             VARBINARY (MAX) NULL,
    [Value48]             VARBINARY (MAX) NULL,
    [Value49]             VARBINARY (MAX) NULL,
    [Value50]             VARBINARY (MAX) NULL,
    [Value51]             VARBINARY (MAX) NULL,
    [Value52]             VARBINARY (MAX) NULL,
    [Value53]             VARBINARY (MAX) NULL,
    [Value54]             VARBINARY (MAX) NULL,
    [Value55]             VARBINARY (MAX) NULL,
    [Value56]             VARBINARY (MAX) NULL,
    [Value57]             VARBINARY (MAX) NULL,
    [Value58]             VARBINARY (MAX) NULL,
    [Value59]             VARBINARY (MAX) NULL,
    [Value60]             VARBINARY (MAX) NULL,
    [Value61]             VARBINARY (MAX) NULL,
    [Value62]             VARBINARY (MAX) NULL,
    [Value63]             VARBINARY (MAX) NULL,
    [Value64]             VARBINARY (MAX) NULL,
    CONSTRAINT [CIX_InstancePromotedPropertiesTable] PRIMARY KEY CLUSTERED ([SurrogateInstanceId] ASC, [PromotionName] ASC) WITH (ALLOW_PAGE_LOCKS = OFF)
);

