//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Framework.DataLayers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPeriode
    {
        public string PeriodeId { get; set; }
        public string PeriodeDescription { get; set; }
        public System.DateTime PeriodeStartDate { get; set; }
        public System.DateTime PeriodeEndDate { get; set; }
    }
}
