//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Framework.DataLayers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductSpecs
    {
        public string PSpecId { get; set; }
        public string ProductId { get; set; }
        public string ProductSpecTitle { get; set; }
        public string ProductSpecValue { get; set; }
    
        public virtual TblProduct TblProduct { get; set; }
    }
}
