//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Framework.DataLayers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblTransaction()
        {
            this.TblProductTransaction = new HashSet<TblProductTransaction>();
        }
    
        public string TransactionId { get; set; }
        public string UserDetailsId { get; set; }
        public string TypeTransaction { get; set; }
        public string TransactionMethod { get; set; }
        public decimal TransactionAmount { get; set; }
        public string TransactionCurrency { get; set; }
        public string TransactionDate { get; set; }
        public string BalanceId { get; set; }
        public string TransactionStatus { get; set; }
    
        public virtual TblBalance TblBalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductTransaction> TblProductTransaction { get; set; }
    }
}
