//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Framework.DataLayers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUserCard
    {
        public string UserCardId { get; set; }
        public string CardType { get; set; }
        public string CardProvider { get; set; }
        public int CardNumber { get; set; }
        public string CardOwner { get; set; }
        public string UserDetailsId { get; set; }
    
        public virtual TblUserDetails TblUserDetails { get; set; }
    }
}
