//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Framework.DataLayers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HelperContext : DbContext
    {
        public HelperContext()
            : base("name=HelperContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblCity> TblCity { get; set; }
        public virtual DbSet<TblCountry> TblCountry { get; set; }
        public virtual DbSet<TblPeriode> TblPeriode { get; set; }
    
        public virtual int sp_Generate_Periode(string periodeId, string periodeDescription, Nullable<System.DateTime> periodeStartDate, Nullable<System.DateTime> periodeEndDate)
        {
            var periodeIdParameter = periodeId != null ?
                new ObjectParameter("periodeId", periodeId) :
                new ObjectParameter("periodeId", typeof(string));
    
            var periodeDescriptionParameter = periodeDescription != null ?
                new ObjectParameter("periodeDescription", periodeDescription) :
                new ObjectParameter("periodeDescription", typeof(string));
    
            var periodeStartDateParameter = periodeStartDate.HasValue ?
                new ObjectParameter("periodeStartDate", periodeStartDate) :
                new ObjectParameter("periodeStartDate", typeof(System.DateTime));
    
            var periodeEndDateParameter = periodeEndDate.HasValue ?
                new ObjectParameter("periodeEndDate", periodeEndDate) :
                new ObjectParameter("periodeEndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Generate_Periode", periodeIdParameter, periodeDescriptionParameter, periodeStartDateParameter, periodeEndDateParameter);
        }
    }
}
