//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Framework.DataLayers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProductContext : DbContext
    {
        public ProductContext()
            : base("name=ProductContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Category> Tbl_Category { get; set; }
        public virtual DbSet<Tbl_Product> Tbl_Product { get; set; }
        public virtual DbSet<Tbl_Product_Category> Tbl_Product_Category { get; set; }
        public virtual DbSet<Tbl_Product_Hot> Tbl_Product_Hot { get; set; }
        public virtual DbSet<Tbl_Product_Image> Tbl_Product_Image { get; set; }
        public virtual DbSet<Tbl_Product_Recommended> Tbl_Product_Recommended { get; set; }
        public virtual DbSet<Tbl_Product_Specs> Tbl_Product_Specs { get; set; }
        public virtual DbSet<Tbl_Product_Variations> Tbl_Product_Variations { get; set; }
    
        public virtual int sp_AddReview(string productId)
        {
            var productIdParameter = productId != null ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AddReview", productIdParameter);
        }
    
        public virtual int sp_Generate_HotProduct(string periodeId)
        {
            var periodeIdParameter = periodeId != null ?
                new ObjectParameter("periodeId", periodeId) :
                new ObjectParameter("periodeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Generate_HotProduct", periodeIdParameter);
        }
    
        public virtual int sp_Generate_ProductRecommend(string periodeId)
        {
            var periodeIdParameter = periodeId != null ?
                new ObjectParameter("periodeId", periodeId) :
                new ObjectParameter("periodeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Generate_ProductRecommend", periodeIdParameter);
        }
    }
}
