//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Framework.DataLayers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserContext : DbContext
    {
        public UserContext()
            : base("name=UserContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Pick_Up_Location> Tbl_Pick_Up_Location { get; set; }
        public virtual DbSet<Tbl_Profile_Image> Tbl_Profile_Image { get; set; }
        public virtual DbSet<Tbl_User_Card> Tbl_User_Card { get; set; }
        public virtual DbSet<Tbl_User_Details> Tbl_User_Details { get; set; }
        public virtual DbSet<Tbl_User_Login> Tbl_User_Login { get; set; }
    }
}
