//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Framework.DataLayers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Pick_Up_Location
    {
        public string Pick_Up_Location_Id { get; set; }
        public string User_Detail_Id { get; set; }
        public string Pick_Up_Location_1 { get; set; }
        public string Pick_Up_Location_2 { get; set; }
        public string Pick_Up_Location_3 { get; set; }
    
        public virtual Tbl_User_Details Tbl_User_Details { get; set; }
    }
}
