//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Framework.DataLayers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Periode
    {
        public string Periode_Id { get; set; }
        public string Periode_Description { get; set; }
        public System.DateTime Periode_StartDate { get; set; }
        public System.DateTime Periode_EndDate { get; set; }
    }
}
