//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Framework.DataLayers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_City
    {
        public int City_Id { get; set; }
        public string City_Name { get; set; }
        public int Country_Id { get; set; }
    
        public virtual Tbl_Country Tbl_Country { get; set; }
    }
}
