//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Framework.DataLayers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Transaction()
        {
            this.Tbl_Product_Transaction = new HashSet<Tbl_Product_Transaction>();
        }
    
        public string Transaction_Id { get; set; }
        public string User_Details_Id { get; set; }
        public string Type_Transaction { get; set; }
        public string Transaction_Method { get; set; }
        public decimal Transaction_Amount { get; set; }
        public string Transaction_Currency { get; set; }
        public string Transaction_Date { get; set; }
        public string Balance_Id { get; set; }
        public string Transaction_Status { get; set; }
    
        public virtual Tbl_Balance Tbl_Balance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Product_Transaction> Tbl_Product_Transaction { get; set; }
    }
}
