//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Framework.DataLayers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Profile_Image
    {
        public string Profile_Image_Id { get; set; }
        public string User_Detail_Id { get; set; }
        public string Profile_Image_Url { get; set; }
        public string Profile_Image_Name { get; set; }
        public int Profile_Image_Size { get; set; }
    
        public virtual Tbl_User_Details Tbl_User_Details { get; set; }
    }
}
