//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Framework.DataLayers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_User_Details()
        {
            this.Tbl_Pick_Up_Location = new HashSet<Tbl_Pick_Up_Location>();
            this.Tbl_Profile_Image = new HashSet<Tbl_Profile_Image>();
            this.Tbl_User_Card = new HashSet<Tbl_User_Card>();
            this.Tbl_User_Login = new HashSet<Tbl_User_Login>();
        }
    
        public string User_Details_Id { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email_Main { get; set; }
        public string Email_Secondary { get; set; }
        public Nullable<int> Phone_Main { get; set; }
        public Nullable<int> Phone_Secondary { get; set; }
        public string Address_Main { get; set; }
        public string Address_Secondary { get; set; }
        public string Address_Third { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Pick_Up_Location> Tbl_Pick_Up_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Profile_Image> Tbl_Profile_Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_User_Card> Tbl_User_Card { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_User_Login> Tbl_User_Login { get; set; }
    }
}
