//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Framework.DataLayers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Product_Transaction
    {
        public string Product_Transaction_Id { get; set; }
        public string Product_Id { get; set; }
        public int Product_Amount { get; set; }
        public string Transaction_Id { get; set; }
    
        public virtual Tbl_Transaction Tbl_Transaction { get; set; }
    }
}
