//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Framework.DataLayers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User_Card
    {
        public string User_Card_Id { get; set; }
        public string Card_Type { get; set; }
        public string Card_Provider { get; set; }
        public int Card_Number { get; set; }
        public string Card_Owner { get; set; }
        public string User_Details_Id { get; set; }
    
        public virtual Tbl_User_Details Tbl_User_Details { get; set; }
    }
}
