//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Framework.DataLayers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUserDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblUserDetails()
        {
            this.TblPickUpLocation = new HashSet<TblPickUpLocation>();
            this.TblProfileImage = new HashSet<TblProfileImage>();
            this.TblUserCard = new HashSet<TblUserCard>();
            this.TblUserLogin = new HashSet<TblUserLogin>();
        }
    
        public string UserDetailsId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string EmailMain { get; set; }
        public string EmailSecondary { get; set; }
        public Nullable<int> PhoneMain { get; set; }
        public Nullable<int> PhoneSecondary { get; set; }
        public string AddressMain { get; set; }
        public string AddressSecondary { get; set; }
        public string AddressThird { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPickUpLocation> TblPickUpLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProfileImage> TblProfileImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUserCard> TblUserCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUserLogin> TblUserLogin { get; set; }
    }
}
