USE EnterpriseDB_Helper

/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 658,'Albury',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 659,'Armidale',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 660,'Bathurst',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 661,'Broken Hill',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 662,'Cessnock',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 663,'Coffs Harbour',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 664,'Dubbo',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 665,'Gosford',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 666,'Goulburn',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 667,'Grafton',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 668,'Griffith',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 669,'Lake Macquarie',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 670,'Lismore',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 671,'Maitland',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 672,'Newcastle',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 673,'Nowra',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 674,'Orange',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 675,'Port Macquarie',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 676,'Queanbeyan',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 677,'Tamworth',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 678,'Tweed Heads',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 679,'Wagga Wagga',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 680,'Wollongong',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 681,'Wyong',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 682,'Darwin',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 683,'Alice Springs',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 684,'Katherine',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 685,'Palmerston',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 686,'Brisbane',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 687,'Bundaberg',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 688,'Cairns',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 689,'Charters Towers',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 690,'Gladstone',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 691,'Gold Coast',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 692,'Gympie',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 693,'Hervey Bay',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 694,'Ipswich',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 695,'Logan City',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 696,'Mackay',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 697,'Maryborough',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 698,'Mount Isa',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 699,'Nambour',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 700,'Redcliffe',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 701,'Rockhampton',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 702,'Sunshine Coast',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 703,'Thuringowa',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 704,'Toowoomba',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 705,'Townsville',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 706,'Adelaide',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 707,'Gladstone',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 708,'Mount Gambier',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 709,'Murray Bridge',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 710,'Port Augusta',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 711,'Port Pirie',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 712,'Port Lincoln',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 713,'Victor Harbor',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 714,'Whyalla',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 715,'Hobart',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 716,'Burnie',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 717,'Clarence',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 718,'Devonport',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 719,'Glenorchy',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 720,'Launceston',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 721,'Melbourne',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 722,'Benalla',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 723,'Ballarat',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 724,'Bendigo',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 725,'Geelong',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 726,'Latrobe City',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 727,'Mildura',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 728,'Shepparton',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 729,'Swan Hill',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 730,'Wangaratta',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 731,'Warrnambool',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 732,'Wodonga',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 733,'Perth',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 734,'Albany',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 735,'Broome',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 736,'Bunbury',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 737,'Geraldton',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 738,'Fremantle',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 739,'Kalgoorlie',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 740,'Mandurah',3);
/* INSERT QUERY */INSERT INTO Tbl_City(City_Id,City_Name,Country_Id) VALUES( 741,'Port Hedland',3);
